FROM python:3.13-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
CMD ["celery", "-A", "tasks.celery", "worker", "--loglevel=info"]
